version: "3"
services:
  app:
      container_name: citypedia
      restart: always
      build: .
      ports:
        - "8000:8000"

  citypedia-db:
      container_name: citypedia-db
      image: mongo
      ports:
        - "27017:27017"

  citypedia_api:
      container_name: api
      image: citypedia_api
      build: ../citypedia-db/
      links:
        - citypedia-db
      ports:
        - "3000:3000"
